[2025-07-29T17:18:49.253+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-29T17:18:46.946429+00:00 [queued]>
[2025-07-29T17:18:49.265+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-29T17:18:46.946429+00:00 [queued]>
[2025-07-29T17:18:49.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-29T17:18:49.287+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_load_orders> on 2025-07-29 17:18:46.946429+00:00
[2025-07-29T17:18:49.298+0000] {standard_task_runner.py:57} INFO - Started process 12855 to run task
[2025-07-29T17:18:49.305+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'orders_dag', 'fetch_and_load_orders', 'manual__2025-07-29T17:18:46.946429+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/orders_dag.py', '--cfg-path', '/tmp/tmp9xlzx1as']
[2025-07-29T17:18:49.310+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask fetch_and_load_orders
[2025-07-29T17:18:49.391+0000] {task_command.py:416} INFO - Running <TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-29T17:18:46.946429+00:00 [running]> on host 02da23aad234
[2025-07-29T17:18:49.531+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='orders_dag' AIRFLOW_CTX_TASK_ID='fetch_and_load_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T17:18:46.946429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-29T17:18:46.946429+00:00'
[2025-07-29T17:18:49.535+0000] {orders_dag.py:32} INFO - ðŸš€ Starting data fetch from API...
[2025-07-29T17:18:49.636+0000] {orders_dag.py:34} INFO - ðŸ”Ž Status Code: 200
[2025-07-29T17:18:49.641+0000] {orders_dag.py:41} INFO - âœ… Successfully parsed JSON. Total Orders: 602
[2025-07-29T17:18:49.890+0000] {orders_dag.py:64} INFO - âœ… Data successfully loaded into PostgreSQL!
[2025-07-29T17:18:49.892+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-29T17:18:49.908+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=orders_dag, task_id=fetch_and_load_orders, execution_date=20250729T171846, start_date=20250729T171849, end_date=20250729T171849
[2025-07-29T17:18:49.961+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-29T17:18:49.987+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
