[2025-07-28T16:38:34.136+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-28T16:38:32.069828+00:00 [queued]>
[2025-07-28T16:38:34.151+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-28T16:38:32.069828+00:00 [queued]>
[2025-07-28T16:38:34.152+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-28T16:38:34.204+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_load_orders> on 2025-07-28 16:38:32.069828+00:00
[2025-07-28T16:38:34.245+0000] {standard_task_runner.py:57} INFO - Started process 71919 to run task
[2025-07-28T16:38:34.257+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'orders_dag', 'fetch_and_load_orders', 'manual__2025-07-28T16:38:32.069828+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/orders_day.py', '--cfg-path', '/tmp/tmps1_iserk']
[2025-07-28T16:38:34.263+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask fetch_and_load_orders
[2025-07-28T16:38:34.482+0000] {task_command.py:416} INFO - Running <TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-28T16:38:32.069828+00:00 [running]> on host 979e7d3a451f
[2025-07-28T16:38:34.744+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='orders_dag' AIRFLOW_CTX_TASK_ID='fetch_and_load_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T16:38:32.069828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T16:38:32.069828+00:00'
[2025-07-28T16:38:34.756+0000] {logging_mixin.py:151} INFO - ðŸš€ Starting data fetch from API...
[2025-07-28T16:38:34.905+0000] {logging_mixin.py:151} INFO - ðŸ”Ž Status Code: 200
[2025-07-28T16:38:34.906+0000] {logging_mixin.py:151} INFO - ðŸ”Ž Raw Response: [{"order_id":"00125cb692d04887809806618a2a145f","user_name":"7ac26eac431c6848694a2de6f0327524","order_status":"delivered","order_date":"3/23/2017 12:21","order_approved_date":"3/23/2017 13:05","pickup...
[2025-07-28T16:38:34.908+0000] {logging_mixin.py:151} INFO - âœ… Successfully parsed JSON. Total Orders: 602
[2025-07-28T16:38:35.054+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/orders_day.py", line 37, in fetch_and_load_orders
    cursor.execute("""
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: "order_date"
LINE 3:             VALUES ('order_id', NULL, NULL, NULL, 'order_dat...
                                                          ^

[2025-07-28T16:38:35.070+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=orders_dag, task_id=fetch_and_load_orders, execution_date=20250728T163832, start_date=20250728T163834, end_date=20250728T163835
[2025-07-28T16:38:35.088+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task fetch_and_load_orders (invalid input syntax for type timestamp: "order_date"
LINE 3:             VALUES ('order_id', NULL, NULL, NULL, 'order_dat...
                                                          ^
; 71919)
[2025-07-28T16:38:35.135+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-28T16:38:35.165+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
